export const STAGES=[{id:"infantil",name:"Infantil",ageMin:3,ageMax:5,icon:"🧒",description:"Rutinas, emociones, juego.",courses:[{id:"inf_3",label:"3 anios"},{id:"inf_4",label:"4 anios"},{id:"inf_5",label:"5 anios"}]},{id:"primaria",name:"Primaria",ageMin:6,ageMax:12,icon:"📚",description:"LOMLOE completo.",courses:[{id:"pri_1",label:"1 Primaria"},{id:"pri_2",label:"2 Primaria"},{id:"pri_3",label:"3 Primaria"},{id:"pri_4",label:"4 Primaria"},{id:"pri_5",label:"5 Primaria"},{id:"pri_6",label:"6 Primaria"}]},{id:"eso",name:"ESO",ageMin:12,ageMax:16,icon:"🎓",description:"Academico y critico.",courses:[{id:"eso_1",label:"1 ESO"},{id:"eso_2",label:"2 ESO"},{id:"eso_3",label:"3 ESO"},{id:"eso_4",label:"4 ESO"}]},{id:"bachillerato",name:"Bachillerato",ageMin:16,ageMax:18,icon:"🏆",description:"Preparacion universitaria.",courses:[{id:"bach_1",label:"1 Bach"},{id:"bach_2",label:"2 Bach"}]}];
export const STAGE_TABS={infantil:[{key:"inicio",label:"Inicio"},{key:"rutinas",label:"Rutinas"},{key:"emociones",label:"Emociones"},{key:"juegos",label:"Juegos"},{key:"tea",label:"Apoyos TEA"},{key:"diario",label:"Diario"},{key:"familia",label:"Familia"},{key:"ajustes",label:"Ajustes"}],primaria:[{key:"inicio",label:"Inicio"},{key:"aprender",label:"Aprender"},{key:"tutor",label:"Tutor emocional"},{key:"profesor",label:"Profesor"},{key:"redes",label:"Redes"},{key:"retos",label:"Retos"},{key:"historias",label:"Historias"},{key:"habitos",label:"Habitos"},{key:"examenes",label:"Examenes"},{key:"juegos",label:"Juegos"},{key:"tea",label:"Apoyos TEA"},{key:"rutinas",label:"Rutinas"},{key:"emociones",label:"Emociones"},{key:"diario",label:"Diario"},{key:"familia",label:"Familia"},{key:"informes",label:"Informes"},{key:"seguridad",label:"Seguridad"},{key:"ajustes",label:"Ajustes"}],eso:[{key:"inicio",label:"Inicio"},{key:"aprender",label:"Aprender"},{key:"redes",label:"Redes"},{key:"retos",label:"Retos"},{key:"habitos",label:"Habitos"},{key:"examenes",label:"Examenes"},{key:"tea",label:"Apoyos TEA"},{key:"emociones",label:"Emociones"},{key:"diario",label:"Diario"},{key:"informes",label:"Informes"},{key:"familia",label:"Familia"},{key:"seguridad",label:"Seguridad"},{key:"ajustes",label:"Ajustes"}],bachillerato:[{key:"inicio",label:"Inicio"},{key:"aprender",label:"Aprender"},{key:"redes",label:"Redes"},{key:"retos",label:"Retos"},{key:"habitos",label:"Habitos"},{key:"examenes",label:"Examenes"},{key:"informes",label:"Informes"},{key:"ajustes",label:"Ajustes"}]};
const SK="tgd_stage_selection";
export function getStageByAge(age){const n=Number(age);return STAGES.find(s=>n>=s.ageMin&&n<=s.ageMax)||null;}
export function getCourseByAge(stage,age){if(!stage)return null;const idx=Math.min(Math.max(0,Number(age)-stage.ageMin),stage.courses.length-1);return stage.courses[idx];}
export function getStageById(id){return STAGES.find(s=>s.id===id)||null;}
export function getAvailableTabs(sid){return STAGE_TABS[sid]||STAGE_TABS.primaria;}
export function saveStageSelection(d){localStorage.setItem(SK,JSON.stringify({...d,savedAt:new Date().toISOString()}));}
export function loadStageSelection(){try{return JSON.parse(localStorage.getItem(SK));}catch{return null;}}
export function clearStageSelection(){localStorage.removeItem(SK);}
