import React,{useState} from "react";
const CK="tgd_consent_accepted",BK="tgd_consent_blocked";
function isBlocked(){try{const d=JSON.parse(localStorage.getItem(BK));if(!d)return false;if(Date.now()-new Date(d.blockedAt).getTime()<86400000)return true;localStorage.removeItem(BK);return false;}catch{return false;}}
function hasConsented(){try{return JSON.parse(localStorage.getItem(CK))?.accepted===true;}catch{return false;}}
export default function ConsentGate({children}){
  const[ok,setOk]=useState(hasConsented());
  const[no,setNo]=useState(isBlocked());
  const[name,setName]=useState("");
  const[detail,setDetail]=useState(false);
  if(no)return(<div className="min-h-screen bg-slate-50 flex items-center justify-center p-6"><div className="max-w-lg w-full text-center space-y-6"><p className="text-5xl">🔒</p><h1 className="text-2xl font-bold">Aplicacion bloqueada</h1><p className="text-slate-600">No se acepto el consentimiento. Podras volver en 24 horas.</p></div></div>);
  if(ok)return<>{children}</>;
  return(<div className="min-h-screen bg-slate-50 flex items-center justify-center p-6"><div className="max-w-2xl w-full space-y-6"><div className="text-center space-y-3"><p className="text-4xl">📋</p><h1 className="text-2xl font-bold">Consentimiento de uso</h1><p className="text-slate-600">El padre, madre o tutor legal debe aceptar antes de usar la app.</p></div><div className="rounded-2xl border bg-white p-6 space-y-4"><h2 className="font-bold text-lg">Sobre la aplicacion</h2><div className="space-y-3 text-sm text-slate-700"><div className="rounded-xl border bg-slate-50 p-4"><p className="font-semibold">Que es</p><p>App educativa para TEA/TGD/Asperger con LOMLOE, rutinas, apoyo emocional y herramientas familias.</p></div><div className="rounded-xl border bg-slate-50 p-4"><p className="font-semibold">Datos</p><p>NO recoge ni envia datos a servidores. Todo cifrado en dispositivo.</p></div><div className="rounded-xl border bg-slate-50 p-4"><p className="font-semibold">Privacidad</p><p>Sin telemetria, publicidad, rastreo. RGPD y LOPDGDD.</p></div><div className="rounded-xl border bg-slate-50 p-4"><p className="font-semibold">Menores 14</p><p>Requiere consentimiento tutor legal (LOPDGDD art. 7).</p></div></div><button onClick={()=>setDetail(!detail)} className="text-sm text-slate-500 underline">{detail?"Ocultar":"Ver detalle"}</button>{detail&&<div className="rounded-xl border bg-slate-50 p-4 text-xs text-slate-600 space-y-1"><p>1. Local-first.</p><p>2. AES-256-GCM + PBKDF2.</p><p>3. Sin email, telefono, IP.</p><p>4. Alias, no nombre.</p><p>5. Revocable desde Ajustes.</p><p>6. Sin IA internet.</p><p>7. Sin publicidad.</p><p>8. No sustituye profesionales.</p></div>}</div><div className="rounded-2xl border bg-white p-6 space-y-3"><h2 className="font-bold">Tutor legal</h2><input type="text" value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre padre/madre/tutor" className="w-full rounded-xl border px-4 py-3"/></div><div className="flex flex-col sm:flex-row gap-4"><button disabled={!name.trim()} onClick={()=>{localStorage.setItem(CK,JSON.stringify({accepted:true,guardian:name.trim(),at:new Date().toISOString()}));setOk(true);}} className="flex-1 rounded-2xl px-6 py-4 bg-emerald-600 text-white font-bold text-lg disabled:opacity-40">ACEPTO</button><button onClick={()=>{localStorage.setItem(BK,JSON.stringify({blockedAt:new Date().toISOString()}));setNo(true);}} className="flex-1 rounded-2xl px-6 py-4 bg-rose-600 text-white font-bold text-lg">NO ACEPTO</button></div><p className="text-center text-xs text-slate-500">NO ACEPTO bloquea 24h.</p></div></div>);
}
